version: '3.4'

services:
  airlinesmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  carsmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  usersmicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

